apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: dev1
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: 303577146899.dkr.ecr.eu-west-1.amazonaws.com/ncloud-gblog-proj:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        # env:
        # - name: url
        #   value: http://my-blog.com