apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: ncloud-wip
  labels:
    app: blog
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: phelun/ghost-init:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        # env:
        # - name: url
        #   value: http://my-blog.com