name: 'infra-platform-cd-plan+apply'

on:
  workflow_dispatch:
    inputs:
      component_path:
        description: 'Which component to apply?'
        default: infra/platform
        required: true
      run_apply:
        description: 'Run Apply? (Y|N)'
        required: false
        default: 'N'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v0.12.31    
          
  apply:
    runs-on: ubuntu-latest
    needs: plan
    if: github.event.inputs.run_apply  == 'Y'
    steps:
      - name: Checkout
        uses: actions/checkout@1.0.0 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v0.12.31 